### ISSUE TITLE
clear and easy clutter install path(s)

### ISSUE THREAD

**Issue by science-girl** [holochain/clutter#68]
As a new clutter user I want the install instructions to not confuse me, and have a very easy time following them while installing them so I can successfully install it.

Current release zip (Feb 13th) is missing the react ui-src folder, meaning the README instructions don't apply.

- [ ] new clutter release zip
- [ ] update readmes to clarify using the source vs. the release version

**Comment by philipbeadle** [comment]
You dont need the ui-src folder as its compiled into UI.

**Comment by zippy** [comment]
so it turns out that we MUST include a ui build in at least the `develop` and `master` branches.  The reason for this is that `hcdev init -cloneExample=clutter` will fail otherwise.  This command does a git clone into `\tmp` and then copies over just the standard set of directories `dna` `test` and `ui`.  And we want people to be able to do that and having a running ui without having to do the npm build step.

**Comment by philipbeadle** [comment]
Can we change hcdev init -cloneExample=clutter to pull from the latest Release?

**Comment by zippy** [comment]
Well, I don't like that because this is already also implemented:  `hcdev init -cloneExample=clutter -fromDevelop` and also `hcdev init -cloneExample=clutter -fromBranch=your-branch-here`   I guess we could figure out a new pattern going forward that takes into account the build cycle, but I don't want to do that last minute before alpha 1.

**Comment by bboyatwork** [comment]
Should we use the current develop branch in order to create the new clutter release zip @zippy @philipbeadle. Thinking the 'archive' link the instructions needs to be updated. Anything specific that needs to be updated in the README you all see, I'm not clear if anything needs to be changed based on the previous comments. @science-girl thoughts?

This is all I've added so far to hopefully clarify some of the wording: 
...
**Dependencies:** If you want to run Clutter locally, you will need `nodejs` (https://nodejs.org/en/) (LTS) installed, with `npm` or `yarn` (https://yarnpkg.com/lang/en/docs/install):

The following commands will clone the latest build of clutter to your machine and then you will either install npm or yarn to build the UI for the app. (this)
```
git clone https://github.com/Holochain/clutter.git
cd clutter/ui-src
npm install # (or yarn install)
npm run build # (or yarn build)
cd ..
```

## Running Clutter (this)
Now if you want to run the app, you can run:
```
hcdev web # if you want to just run it temporarily and test it out, with scratch data
```
or
```
hcd web # if you want to really start to use the app
```

**Comment by science-girl** [comment]
I believe once we push to master and set tag to true, a new release will be
created.
